//! SPDX-License-Identifier: GPL-3.0-or-later

#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'aabb_pool''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'aabb_pool''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'obb_pool''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'obb_pool''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'brush_pool''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'brush_pool''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'partition_pool''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'partition_pool''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'double_sphere_pool''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'double_sphere_pool''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'cylinder_pool''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'cylinder_pool''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'polygon_cylinder_pool''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'polygon_cylinder_pool''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'g_VehicleParameters''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'g_VehicleParameters''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'g_rb_vehicle_list''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'g_rb_vehicle_list''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'g_auto_rigid_body_allocator''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'g_auto_rigid_body_allocator''")();
}

#endif // __UNIMPLEMENTED__
#ifdef    __UNIMPLEMENTED__

void `dynamic initializer for 'g_ragdoll_body_pool''()
{
  return Zynamic::Forward<void ()>(L"`dynamic initializer for 'g_ragdoll_body_pool''")();
}

#endif // __UNIMPLEMENTED__